In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Steps :---

# 1. cleanind (Null , outliesrs)
# 2. merge
# 3. feature selection
    # corelation 
    # chi-square
    # anova
    # vif
# 4. scaling
    # Standardazation
    # Normalization

# 5. feature  transformation (cat to nnum)
    # label encoding
    # one hot encoding
    # manual fill
    # ordinal encoding

# 6. EDA
    # Chart , graph and dashboard

In [3]:
# For Ml ;-
  # Prediction using ml library
  # model evolution using evolution matrix

In [4]:
# Banking terms 

# asset :-
# loan :- home loan , ed loan , per loan

# liablity - sav account , account , fd , rd

In [5]:
df2 = pd.read_excel("case_study1.xlsx")      # Bank Internal Data 
df1 = pd.read_excel("case_study2.xlsx")      # external data Civial

In [6]:
df2

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.00,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0,2,0,0,0,0,3,1,24,5
51332,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0,2,0,0,0,2,2,0,74,7
51333,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,0,2,0,0,0,0,2,0,9,5
51334,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0,2,0,0,0,0,2,0,15,8
51335,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,0,0,0,0,1,0,0,20,20

In [7]:
df1

,PROSPECTID,time_since_recent_payment,time_since_first_deliquency,time_since_recent_deliquency,num_times_delinquent,max_delinquency_level,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,...,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,max_unsec_exposure_inPct,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,35,15,11,29,29,0,0,0,...,0.0,0.0,0.0,13.333,1,0,PL,PL,696,P2
1,2,47,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.860,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,11,3,9,25,25,1,9,8,...,0.0,0.0,0.0,5741.667,1,0,ConsumerLoan,others,693,P2
3,4,-99999,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,9.900,0,0,others,others,673,P2
4,5,583,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,24,23,2,24,24,0,0,0,...,0.0,0.0,0.0,1.661,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,0.520,0,0,others,others,702,P1
51333,51334,32,-99999,-99999,0,-99999,0,0,0,0,...,0.0,1.0,0.0,0.567,0,0,ConsumerLoan,others,661,P3
51334,51335,58,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,1.202,0,0,ConsumerLoan,others,686,P2
51335,51336,74,-99999,-99999,0,-99999,0,0,0,0,...,0.0,0.0,0.0,-99999.000,0,0,others,others,681,P2

In [9]:
df2.isnull().sum()

PROSPECTID              0
Total_TL                0
Tot_Closed_TL           0
Tot_Active_TL           0
Total_TL_opened_L6M     0
Tot_TL_closed_L6M       0
pct_tl_open_L6M         0
pct_tl_closed_L6M       0
pct_active_tl           0
pct_closed_tl           0
Total_TL_opened_L12M    0
Tot_TL_closed_L12M      0
pct_tl_open_L12M        0
pct_tl_closed_L12M      0
Tot_Missed_Pmnt         0
Auto_TL                 0
CC_TL                   0
Consumer_TL             0
Gold_TL                 0
Home_TL                 0
PL_TL                   0
Secured_TL              0
Unsecured_TL            0
Other_TL                0
Age_Oldest_TL           0
Age_Newest_TL           0
dtype: int64

In [10]:
df1.isnull().sum()

PROSPECTID                      0
time_since_recent_payment       0
time_since_first_deliquency     0
time_since_recent_deliquency    0
num_times_delinquent            0
                               ..
GL_Flag                         0
last_prod_enq2                  0
first_prod_enq2                 0
Credit_Score                    0
Approved_Flag                   0
Length: 62, dtype: int64

In [11]:
for i in df1.columns:
    print(df1[i].isnull().sum())

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [12]:
for i in df1.columns:
    print((df1[i] == -99999).sum())

0
4291
35949
35949
0
35949
0
0
0
0
12890
10832
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
6321
6321
6321
6321
6321
6321
6321
6321
6321
6321
6321
0
0
0
0
0
0
0
0
72
47636
0
44435
0
0
0
0
0
23178
0
0
0
0
0
0

In [13]:
for i in df.columns:
    print((df[i] == -99999).sum())

NameError: name 'df' is not defined

In [14]:
# -99999 for df1

for i in df1.columns:
    if (df1[i] == -99999).sum() >0:
        print(i," ------- ",(df1[i] == -99999 ).sum(), "----",(df1[i] == -99999 ).sum()/len(df1))

time_since_recent_payment  -------  4291 ---- 0.08358656693158797
time_since_first_deliquency  -------  35949 ---- 0.7002688172043011
time_since_recent_deliquency  -------  35949 ---- 0.7002688172043011
max_delinquency_level  -------  35949 ---- 0.7002688172043011
max_deliq_6mts  -------  12890 ---- 0.25109085242325074
max_deliq_12mts  -------  10832 ---- 0.21100202586878603
tot_enq  -------  6321 ---- 0.12312996727442731
CC_enq  -------  6321 ---- 0.12312996727442731
CC_enq_L6m  -------  6321 ---- 0.12312996727442731
CC_enq_L12m  -------  6321 ---- 0.12312996727442731
PL_enq  -------  6321 ---- 0.12312996727442731
PL_enq_L6m  -------  6321 ---- 0.12312996727442731
PL_enq_L12m  -------  6321 ---- 0.12312996727442731
time_since_recent_enq  -------  6321 ---- 0.12312996727442731
enq_L12m  -------  6321 ---- 0.12312996727442731
enq_L6m  -------  6321 ---- 0.12312996727442731
enq_L3m  -------  6321 ---- 0.12312996727442731
pct_currentBal_all_TL  -------  72 ---- 0.001402524544179523
CC_utilization  -------  47636 ---- 0.9279258220352189
PL_utilization  -------  44435 ---- 0.8655719183419043
max_unsec_exposure_inPct  -------  23178 ---- 0.45149602618045814

In [15]:
# -99999 for df

x=[]
for i in df2.columns:
    if (df2[i] == -99999).sum() >0:
        print(i," ------- ",(df2[i] == -99999 ).sum() ,"-----" ,(df2[i] == -99999 ).sum()/len(df2))
        x.append(i)

Age_Oldest_TL  -------  40 ----- 0.0007791803023219573
Age_Newest_TL  -------  40 ----- 0.0007791803023219573

In [16]:
# give index of df , -99999

df2[(df2["Age_Oldest_TL"] == -99999 )].index

Index([  532,   804,  1179,  3299,  5694,  5951,  9079, 10003, 10859, 12017,
       12478, 12603, 15248, 16903, 21698, 22649, 23272, 24409, 25778, 26228,
       28495, 29034, 29838, 29900, 30732, 32048, 33012, 34897, 36155, 36705,
       37908, 39097, 39747, 41266, 42863, 45680, 46777, 46954, 50291, 50804],
      dtype='int64')

In [17]:
# deleting in df

df2.drop(df2[(df2["Age_Oldest_TL"] == -99999 )].index,axis=0,inplace=True)

In [18]:
df2

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,CC_TL,Consumer_TL,Gold_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,Other_TL,Age_Oldest_TL,Age_Newest_TL
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0,0,1,0,4,1,4,0,72,18
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,1,0,0,0,0,1,0,7,7
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0,6,1,0,0,2,6,0,47,2
3,4,1,0,1,1,0,1.000,0.00,1.000,0.000,...,0,0,0,0,0,0,1,1,5,5
4,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0,0,0,0,0,3,0,2,131,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0,2,0,0,0,0,3,1,24,5
51332,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0,2,0,0,0,2,2,0,74,7
51333,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,0,2,0,0,0,0,2,0,9,5
51334,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0,2,0,0,0,0,2,0,15,8
51335,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0,0,0,0,0,1,0,0,20,20

In [19]:
#  delete column who has greater than 10000 values of -99999 for df1
x = []
for i in df1.columns:
    if (df1[i] == -99999).sum() >10000:
        print(i," ------- ",(df1[i] == -99999 ).sum(), "----",(df1[i] == -99999 ).sum()/len(df1))
        x.append(i)

time_since_first_deliquency  -------  35949 ---- 0.7002688172043011
time_since_recent_deliquency  -------  35949 ---- 0.7002688172043011
max_delinquency_level  -------  35949 ---- 0.7002688172043011
max_deliq_6mts  -------  12890 ---- 0.25109085242325074
max_deliq_12mts  -------  10832 ---- 0.21100202586878603
CC_utilization  -------  47636 ---- 0.9279258220352189
PL_utilization  -------  44435 ---- 0.8655719183419043
max_unsec_exposure_inPct  -------  23178 ---- 0.45149602618045814

In [20]:
df1.drop(x,axis=1,inplace=True)

In [21]:
df1

,PROSPECTID,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,11,29,0,0,0,0,0,21,...,0.0,0.0,0.0,0.0,1,0,PL,PL,696,P2
1,2,47,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,9,25,1,9,8,0,0,10,...,0.0,0.0,0.0,0.0,1,0,ConsumerLoan,others,693,P2
3,4,-99999,0,0,0,0,0,0,0,5,...,0.0,0.0,0.0,0.0,0,0,others,others,673,P2
4,5,583,0,0,0,0,0,0,0,53,...,0.0,0.0,0.0,0.0,0,0,AL,AL,753,P1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,2,24,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,0,0,0,0,0,0,0,6,...,0.0,0.0,0.0,0.0,0,0,others,others,702,P1
51333,51334,32,0,0,0,0,0,0,0,0,...,1.0,0.0,1.0,0.0,0,0,ConsumerLoan,others,661,P3
51334,51335,58,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0,0,ConsumerLoan,others,686,P2
51335,51336,74,0,0,0,0,0,0,0,18,...,0.0,0.0,0.0,0.0,0,0,others,others,681,P2

In [22]:
#  delete column who has greater than 10000 values of -99999 for df1
x = []
for i in df1.columns:
    if (df1[i] == -99999).sum() >0:
        print(i," ------- ",(df1[i] == -99999 ).sum(), "----",(df1[i] == -99999 ).sum()/len(df1))
        x.append(i)

time_since_recent_payment  -------  4291 ---- 0.08358656693158797
tot_enq  -------  6321 ---- 0.12312996727442731
CC_enq  -------  6321 ---- 0.12312996727442731
CC_enq_L6m  -------  6321 ---- 0.12312996727442731
CC_enq_L12m  -------  6321 ---- 0.12312996727442731
PL_enq  -------  6321 ---- 0.12312996727442731
PL_enq_L6m  -------  6321 ---- 0.12312996727442731
PL_enq_L12m  -------  6321 ---- 0.12312996727442731
time_since_recent_enq  -------  6321 ---- 0.12312996727442731
enq_L12m  -------  6321 ---- 0.12312996727442731
enq_L6m  -------  6321 ---- 0.12312996727442731
enq_L3m  -------  6321 ---- 0.12312996727442731
pct_currentBal_all_TL  -------  72 ---- 0.001402524544179523

In [23]:
# Now check this empty rows are common or not 


df1 = df1[df1["CC_enq_L12m"] != -99999 ]

In [24]:
df1

,PROSPECTID,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,11,29,0,0,0,0,0,21,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,47,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,9,25,1,9,8,0,0,10,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
4,5,583,0,0,0,0,0,0,0,53,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
5,6,245,14,270,0,0,0,13,11,5,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,2,24,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,0,0,0,0,0,0,0,6,...,0.0,0.0,0.000,0.0,0,0,others,others,702,P1
51333,51334,32,0,0,0,0,0,0,0,0,...,1.0,0.0,1.000,0.0,0,0,ConsumerLoan,others,661,P3
51334,51335,58,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,686,P2
51335,51336,74,0,0,0,0,0,0,0,18,...,0.0,0.0,0.000,0.0,0,0,others,others,681,P2

In [25]:
#  check

for i in df1.columns:
    if (df1[i] == -99999).sum() >0:
        print(i," ------- ",(df1[i] == -99999 ).sum(), "----",(df1[i] == -99999 ).sum()/len(df1))

time_since_recent_payment  -------  2914 ---- 0.06473397756303455
pct_currentBal_all_TL  -------  42 ---- 0.0009330223258913696

In [26]:
# check

for i in df2.columns:
    if (df2[i] == -99999).sum() >0:
        print(i," ------- ",(df2[i] == -99999 ).sum(), "----",(df2[i] == -99999 ).sum()/len(df2))

In [27]:
a=set(df1[(df1["pct_currentBal_all_TL"] == -99999 )].index) & set(df1[(df1["time_since_recent_payment"] == -99999 )].index)
a=list(a)

In [28]:
df1.drop(a,axis=0,inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_7360\1479442252.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(a,axis=0,inplace=True)

In [29]:
#  check

for i in df1.columns:
    if (df1[i] == -99999).sum() >0:
        print(i," ------- ",(df1[i] == -99999 ).sum(), "----",(df1[i] == -99999 ).sum()/len(df1))

time_since_recent_payment  -------  2907 ---- 0.06458851759687166
pct_currentBal_all_TL  -------  35 ---- 0.0007776395307500888

In [30]:
df1

,PROSPECTID,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,11,29,0,0,0,0,0,21,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,47,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,9,25,1,9,8,0,0,10,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
4,5,583,0,0,0,0,0,0,0,53,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
5,6,245,14,270,0,0,0,13,11,5,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,2,24,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,0,0,0,0,0,0,0,6,...,0.0,0.0,0.000,0.0,0,0,others,others,702,P1
51333,51334,32,0,0,0,0,0,0,0,0,...,1.0,0.0,1.000,0.0,0,0,ConsumerLoan,others,661,P3
51334,51335,58,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,686,P2
51335,51336,74,0,0,0,0,0,0,0,18,...,0.0,0.0,0.000,0.0,0,0,others,others,681,P2

In [31]:
df1.drop(df1[(df1["time_since_recent_payment"] == -99999 )].index ,axis=0,inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_7360\3651105504.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(df1[(df1["time_since_recent_payment"] == -99999 )].index ,axis=0,inplace=True)

In [32]:
df1.drop(df1[(df1["pct_currentBal_all_TL"] == -99999 )].index ,axis=0,inplace=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_7360\797795495.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(df1[(df1["pct_currentBal_all_TL"] == -99999 )].index ,axis=0,inplace=True)

In [33]:
df1

,PROSPECTID,time_since_recent_payment,num_times_delinquent,max_recent_level_of_deliq,num_deliq_6mts,num_deliq_12mts,num_deliq_6_12mts,num_times_30p_dpd,num_times_60p_dpd,num_std,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,549,11,29,0,0,0,0,0,21,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,47,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,302,9,25,1,9,8,0,0,10,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
4,5,583,0,0,0,0,0,0,0,53,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
5,6,245,14,270,0,0,0,13,11,5,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51331,51332,15,2,24,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
51332,51333,57,0,0,0,0,0,0,0,6,...,0.0,0.0,0.000,0.0,0,0,others,others,702,P1
51333,51334,32,0,0,0,0,0,0,0,0,...,1.0,0.0,1.000,0.0,0,0,ConsumerLoan,others,661,P3
51334,51335,58,0,0,0,0,0,0,0,0,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,686,P2
51335,51336,74,0,0,0,0,0,0,0,18,...,0.0,0.0,0.000,0.0,0,0,others,others,681,P2

In [34]:
# -99999 for df1

for i in df1.columns:
    if (df1[i] == -99999).sum() >0:
        print(i," ------- ",(df1[i] == -99999 ).sum(), "----",(df1[i] == -99999 ).sum()/len(df1))

In [35]:
# -99999 for df

for i in df2.columns:
    if (df2[i] == -99999).sum() >0:
        print(i," ------- ",(df2[i] == -99999 ).sum(), "----",(df2[i] == -99999 ).sum()/len(df2))

# Here Null values are cleaned:----

In [36]:
# Joins :=

In [37]:
df=pd.merge(df2, df1, right_on='PROSPECTID',left_on='PROSPECTID', how='inner')

In [38]:
df

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
42060,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0.0,0.0,0.000,0.0,0,0,others,others,702,P1
42061,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,1.0,0.0,1.000,0.0,0,0,ConsumerLoan,others,661,P3
42062,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,686,P2
42063,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,others,others,681,P2

# chisqare test:--

In [39]:
for i in df.columns:
    print(i,"----------",df[i].dtype,"-----",df[i][0])

PROSPECTID ---------- int64 ----- 1
Total_TL ---------- int64 ----- 5
Tot_Closed_TL ---------- int64 ----- 4
Tot_Active_TL ---------- int64 ----- 1
Total_TL_opened_L6M ---------- int64 ----- 0
Tot_TL_closed_L6M ---------- int64 ----- 0
pct_tl_open_L6M ---------- float64 ----- 0.0
pct_tl_closed_L6M ---------- float64 ----- 0.0
pct_active_tl ---------- float64 ----- 0.2
pct_closed_tl ---------- float64 ----- 0.8
Total_TL_opened_L12M ---------- int64 ----- 0
Tot_TL_closed_L12M ---------- int64 ----- 0
pct_tl_open_L12M ---------- float64 ----- 0.0
pct_tl_closed_L12M ---------- float64 ----- 0.0
Tot_Missed_Pmnt ---------- int64 ----- 0
Auto_TL ---------- int64 ----- 0
CC_TL ---------- int64 ----- 0
Consumer_TL ---------- int64 ----- 0
Gold_TL ---------- int64 ----- 1
Home_TL ---------- int64 ----- 0
PL_TL ---------- int64 ----- 4
Secured_TL ---------- int64 ----- 1
Unsecured_TL ---------- int64 ----- 4
Other_TL ---------- int64 ----- 0
Age_Oldest_TL ---------- int64 ----- 72
Age_Newest_TL ---------- int64 ----- 18
time_since_recent_payment ---------- int64 ----- 549
num_times_delinquent ---------- int64 ----- 11
max_recent_level_of_deliq ---------- int64 ----- 29
num_deliq_6mts ---------- int64 ----- 0
num_deliq_12mts ---------- int64 ----- 0
num_deliq_6_12mts ---------- int64 ----- 0
num_times_30p_dpd ---------- int64 ----- 0
num_times_60p_dpd ---------- int64 ----- 0
num_std ---------- int64 ----- 21
num_std_6mts ---------- int64 ----- 5
num_std_12mts ---------- int64 ----- 11
num_sub ---------- int64 ----- 0
num_sub_6mts ---------- int64 ----- 0
num_sub_12mts ---------- int64 ----- 0
num_dbt ---------- int64 ----- 0
num_dbt_6mts ---------- int64 ----- 0
num_dbt_12mts ---------- int64 ----- 0
num_lss ---------- int64 ----- 0
num_lss_6mts ---------- int64 ----- 0
num_lss_12mts ---------- int64 ----- 0
recent_level_of_deliq ---------- int64 ----- 29
tot_enq ---------- int64 ----- 6
CC_enq ---------- int64 ----- 0
CC_enq_L6m ---------- int64 ----- 0
CC_enq_L12m ---------- int64 ----- 0
PL_enq ---------- int64 ----- 6
PL_enq_L6m ---------- int64 ----- 0
PL_enq_L12m ---------- int64 ----- 0
time_since_recent_enq ---------- int64 ----- 566
enq_L12m ---------- int64 ----- 0
enq_L6m ---------- int64 ----- 0
enq_L3m ---------- int64 ----- 0
MARITALSTATUS ---------- object ----- Married
EDUCATION ---------- object ----- 12TH
AGE ---------- int64 ----- 48
GENDER ---------- object ----- M
NETMONTHLYINCOME ---------- int64 ----- 51000
Time_With_Curr_Empr ---------- int64 ----- 114
pct_of_active_TLs_ever ---------- float64 ----- 0.2
pct_opened_TLs_L6m_of_L12m ---------- float64 ----- 0.0
pct_currentBal_all_TL ---------- float64 ----- 0.798
CC_Flag ---------- int64 ----- 0
PL_Flag ---------- int64 ----- 1
pct_PL_enq_L6m_of_L12m ---------- float64 ----- 0.0
pct_CC_enq_L6m_of_L12m ---------- float64 ----- 0.0
pct_PL_enq_L6m_of_ever ---------- float64 ----- 0.0
pct_CC_enq_L6m_of_ever ---------- float64 ----- 0.0
HL_Flag ---------- int64 ----- 1
GL_Flag ---------- int64 ----- 0
last_prod_enq2 ---------- object ----- PL
first_prod_enq2 ---------- object ----- PL
Credit_Score ---------- int64 ----- 696
Approved_Flag ---------- object ----- P2

In [40]:
x=[]
for i in df.columns:
    if df[i].dtype == "object":
        print(i)
        x.append(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

In [41]:
 pd.crosstab(df["MARITALSTATUS"],df["Approved_Flag"])

Approved_Flag    P1     P2    P3    P4
MARITALSTATUS
Married        4435  18718  4387  3346
Single          473   6734  2053  1918

In [42]:
 pd.crosstab(df["EDUCATION"],df["Approved_Flag"])

Approved_Flag     P1    P2    P3    P4
EDUCATION
12TH            1191  7326  1881  1305
GRADUATE        1766  8266  2136  1972
OTHERS           310  1401   327   253
POST-GRADUATE    304  1114   251   229
PROFESSIONAL      44   130    31    14
SSC              761  4518  1104   858
UNDER GRADUATE   532  2697   710   633

In [43]:
# # Using Chi square with the help of python

# from scipy.stats import chi2_contingency

# chi2, p, dof, expected = chi2_contingency(pd.crosstab(df["Outlook"],df["Play_Tennis"]))

In [44]:
from scipy.stats import chi2_contingency

In [45]:
chi2,p,dof,excepted = chi2_contingency(pd.crosstab(df["EDUCATION"],df["Approved_Flag"]))

In [46]:
chi2

np.float64(187.81675366240617)

In [47]:
p

np.float64(2.6942265249737532e-30)

In [48]:
for i in x:
    chi2,p,dof,excepted = chi2_contingency(pd.crosstab(df[i],df["Approved_Flag"]))
    print(i)
    print("chi2 :-",chi2,"---  p:-",p)

MARITALSTATUS
chi2 :- 1076.9871387543772 ---  p:- 3.578180861038862e-233
EDUCATION
chi2 :- 187.81675366240617 ---  p:- 2.6942265249737532e-30
GENDER
chi2 :- 24.56031272141628 ---  p:- 1.907936100186563e-05
last_prod_enq2
chi2 :- 2444.9571510235596 ---  p:- 0.0
first_prod_enq2
chi2 :- 1387.5609151031795 ---  p:- 7.84997610555419e-287
Approved_Flag
chi2 :- 126192.0 ---  p:- 0.0

In [49]:
# Here we can see that , p value hase less than 0.5 , so it reject the null hypothessis and relation is present ,so we cant remove any column

In [50]:
chi2,p,dof,excepted = chi2_contingency(pd.crosstab(df["last_prod_enq2"],df["Approved_Flag"]))

In [51]:
p

np.float64(0.0)

In [52]:
excepted

array([[ 157.86715481,  818.67050209,  207.14435146,  169.31799163],
       [ 256.11116394, 1328.14615824,  336.05458349,  274.68809433],
       [1922.87561811, 9971.68505135, 2523.08862685, 2062.35070369],
       [  96.84385698,  502.21472043,  127.07303157,  103.86839102],
       [ 881.27909852, 4570.15395588, 1156.3645873 ,  945.20235831],
       [1593.02310765, 8261.12961202, 2090.27481932, 1708.57246101]])

# VIF

In [53]:
# Those column which has numeric data type 

x=[]
for i in df.columns:
    if df[i].dtype!="object":
        print(i,"---", df[i].dtype)
        x.append(i)

PROSPECTID --- int64
Total_TL --- int64
Tot_Closed_TL --- int64
Tot_Active_TL --- int64
Total_TL_opened_L6M --- int64
Tot_TL_closed_L6M --- int64
pct_tl_open_L6M --- float64
pct_tl_closed_L6M --- float64
pct_active_tl --- float64
pct_closed_tl --- float64
Total_TL_opened_L12M --- int64
Tot_TL_closed_L12M --- int64
pct_tl_open_L12M --- float64
pct_tl_closed_L12M --- float64
Tot_Missed_Pmnt --- int64
Auto_TL --- int64
CC_TL --- int64
Consumer_TL --- int64
Gold_TL --- int64
Home_TL --- int64
PL_TL --- int64
Secured_TL --- int64
Unsecured_TL --- int64
Other_TL --- int64
Age_Oldest_TL --- int64
Age_Newest_TL --- int64
time_since_recent_payment --- int64
num_times_delinquent --- int64
max_recent_level_of_deliq --- int64
num_deliq_6mts --- int64
num_deliq_12mts --- int64
num_deliq_6_12mts --- int64
num_times_30p_dpd --- int64
num_times_60p_dpd --- int64
num_std --- int64
num_std_6mts --- int64
num_std_12mts --- int64
num_sub --- int64
num_sub_6mts --- int64
num_sub_12mts --- int64
num_dbt --- int64
num_dbt_6mts --- int64
num_dbt_12mts --- int64
num_lss --- int64
num_lss_6mts --- int64
num_lss_12mts --- int64
recent_level_of_deliq --- int64
tot_enq --- int64
CC_enq --- int64
CC_enq_L6m --- int64
CC_enq_L12m --- int64
PL_enq --- int64
PL_enq_L6m --- int64
PL_enq_L12m --- int64
time_since_recent_enq --- int64
enq_L12m --- int64
enq_L6m --- int64
enq_L3m --- int64
AGE --- int64
NETMONTHLYINCOME --- int64
Time_With_Curr_Empr --- int64
pct_of_active_TLs_ever --- float64
pct_opened_TLs_L6m_of_L12m --- float64
pct_currentBal_all_TL --- float64
CC_Flag --- int64
PL_Flag --- int64
pct_PL_enq_L6m_of_L12m --- float64
pct_CC_enq_L6m_of_L12m --- float64
pct_PL_enq_L6m_of_ever --- float64
pct_CC_enq_L6m_of_ever --- float64
HL_Flag --- int64
GL_Flag --- int64
Credit_Score --- int64

In [54]:
df[x]

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_currentBal_all_TL,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,Credit_Score
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0.798,0,1,0.0,0.0,0.000,0.0,1,0,696
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.370,0,0,0.0,0.0,0.000,0.0,0,0,685
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0.585,0,0,0.0,0.0,0.000,0.0,1,0,693
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0.000,0,0,0.0,0.0,0.000,0.0,0,0,753
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,...,0.000,0,0,1.0,0.0,0.429,0.0,1,0,668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0.230,0,0,0.0,0.0,0.000,0.0,0,0,650
42060,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0.660,0,0,0.0,0.0,0.000,0.0,0,0,702
42061,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,0.428,0,0,1.0,0.0,1.000,0.0,0,0,661
42062,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0.143,0,0,0.0,0.0,0.000,0.0,0,0,686
42063,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.333,0,0,0.0,0.0,0.000,0.0,0,0,681

In [55]:
df[x].corr()

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_currentBal_all_TL,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,Credit_Score
PROSPECTID,1.000000,-0.001844,0.000137,-0.006074,-0.002344,0.003793,0.000163,0.006426,-0.006403,0.006403,...,0.003446,0.005456,-0.001865,0.001616,0.005911,0.000090,0.005962,0.002923,0.000305,-0.007587
Total_TL,-0.001844,1.000000,0.956023,0.662352,0.413593,0.453602,-0.062464,-0.015699,-0.272108,0.272108,...,0.001259,0.171139,0.231757,0.064139,0.102004,0.020749,0.075026,0.442653,0.108299,0.198477
Tot_Closed_TL,0.000137,0.956023,1.000000,0.413492,0.239684,0.390155,-0.135335,0.012192,-0.393123,0.393123,...,0.001335,0.099666,0.162370,0.016964,0.052815,-0.018390,0.032148,0.444720,0.078980,0.202856
Tot_Active_TL,-0.006074,0.662352,0.413492,1.000000,0.671723,0.411560,0.151789,-0.079883,0.159460,-0.159460,...,0.000498,0.276702,0.304717,0.155782,0.181756,0.111390,0.150795,0.238189,0.134460,0.097981
Total_TL_opened_L6M,-0.002344,0.413593,0.239684,0.671723,1.000000,0.504402,0.552977,0.078738,0.085263,-0.085263,...,-0.002067,0.137812,0.243334,0.270036,0.223240,0.249575,0.213780,0.144407,0.008026,-0.115839
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
pct_PL_enq_L6m_of_ever,0.000090,0.020749,-0.018390,0.111390,0.249575,0.077238,0.296453,0.054255,0.085416,-0.085416,...,0.004579,0.022263,0.136732,0.962538,0.170931,1.000000,0.172216,-0.016778,-0.038832,-0.388061
pct_CC_enq_L6m_of_ever,0.005962,0.075026,0.032148,0.150795,0.213780,0.109235,0.153742,0.026543,0.039895,-0.039895,...,0.000288,0.250996,0.122264,0.184946,0.960189,0.172216,1.000000,0.009587,0.004789,-0.202450
HL_Flag,0.002923,0.442653,0.444720,0.238189,0.144407,0.155547,-0.092713,-0.046453,-0.332718,0.332718,...,0.005557,0.023879,0.037668,-0.003876,0.015793,-0.016778,0.009587,1.000000,0.038070,0.146877
GL_Flag,0.000305,0.108299,0.078980,0.134460,0.008026,0.012632,-0.056438,-0.050074,0.001389,-0.001389,...,-0.000579,0.082596,0.077820,-0.027014,0.013226,-0.038832,0.004789,0.038070,1.000000,0.169684
Credit_Score,-0.007587,0.198477,0.202856,0.097981,-0.115839,0.023735,-0.254776,-0.076272,-0.177621,0.177621,...,-0.003631,0.021345,0.048567,-0.379213,-0.200482,-0.388061,-0.202450,0.146877,0.169684,1.000000

In [56]:
# Vif :- variance inflation factor

# handle multicolenarity

# multiconearity :- jab 2 column ek jasa behave kra

In [57]:
df

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,last_prod_enq2,first_prod_enq2,Credit_Score,Approved_Flag
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,0.0,0.0,0.000,0.0,1,0,PL,PL,696,P2
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,685,P2
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,1,0,ConsumerLoan,others,693,P2
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,0.0,0.0,0.000,0.0,0,0,AL,AL,753,P1
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,...,1.0,0.0,0.429,0.0,1,0,ConsumerLoan,PL,668,P3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,ConsumerLoan,650,P4
42060,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,0.0,0.0,0.000,0.0,0,0,others,others,702,P1
42061,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,1.0,0.0,1.000,0.0,0,0,ConsumerLoan,others,661,P3
42062,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,0.0,0.0,0.000,0.0,0,0,ConsumerLoan,others,686,P2
42063,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,0.0,0.0,0.000,0.0,0,0,others,others,681,P2

In [58]:
numeric_columns=[]
for i in df.columns:
    if df[i].dtype!="object" and i not in ["PROSPECTID","Approved_Flag"]:  
        numeric_columns.append(i)

dfn = df[numeric_columns]
dfn

,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,Total_TL_opened_L12M,...,pct_currentBal_all_TL,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_L12m,pct_CC_enq_L6m_of_L12m,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag,Credit_Score
0,5,4,1,0,0,0.000,0.00,0.200,0.800,0,...,0.798,0,1,0.0,0.0,0.000,0.0,1,0,696
1,1,0,1,0,0,0.000,0.00,1.000,0.000,1,...,0.370,0,0,0.0,0.0,0.000,0.0,0,0,685
2,8,0,8,1,0,0.125,0.00,1.000,0.000,2,...,0.585,0,0,0.0,0.0,0.000,0.0,1,0,693
3,3,2,1,0,0,0.000,0.00,0.333,0.667,0,...,0.000,0,0,0.0,0.0,0.000,0.0,0,0,753
4,6,5,1,0,0,0.000,0.00,0.167,0.833,0,...,0.000,0,0,1.0,0.0,0.429,0.0,1,0,668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,3,0,3,1,0,0.333,0.00,1.000,0.000,1,...,0.230,0,0,0.0,0.0,0.000,0.0,0,0,650
42060,4,2,2,0,1,0.000,0.25,0.500,0.500,2,...,0.660,0,0,0.0,0.0,0.000,0.0,0,0,702
42061,2,1,1,1,1,0.500,0.50,0.500,0.500,2,...,0.428,0,0,1.0,0.0,1.000,0.0,0,0,661
42062,2,1,1,0,0,0.000,0.00,0.500,0.500,1,...,0.143,0,0,0.0,0.0,0.000,0.0,0,0,686
42063,1,0,1,0,0,0.000,0.00,1.000,0.000,0,...,0.333,0,0,0.0,0.0,0.000,0.0,0,0,681

In [59]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [60]:
total_columns = dfn.shape[1]
column_to_be_kept = []
column_index = 0

for i in range(0,total_columns):
    vif_value = variance_inflation_factor(dfn,column_index)
    print(column_index,"---------",vif_value)

    if vif_value <= 6:
        column_to_be_kept.append(numeric_columns[i])
        column_index = column_index +1 

    else:
        dfn = dfn.drop([numeric_columns[i]],axis=1)

C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --------- inf

C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

0 --------- inf
0 --------- 11.320180023967996
0 --------- 8.363698035000336
0 --------- 6.520647877790928
0 --------- 5.149501618212625
1 --------- 2.611111040579735

C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

2 --------- inf
2 --------- 1788.7926256209232
2 --------- 8.601028256477228
2 --------- 3.8328007921530785
3 --------- 6.099653381646727
3 --------- 5.581352009642766
4 --------- 1.985584353098778

C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

5 --------- inf
5 --------- 4.809538302819343
6 --------- 23.270628983464636
6 --------- 30.595522588100053
6 --------- 4.384346405965583
7 --------- 3.064658415523423
8 --------- 2.898639771299251
9 --------- 4.377876915347324
10 --------- 2.2078535836958433
11 --------- 4.916914200506864
12 --------- 5.214702030064725
13 --------- 3.3861625024231476
14 --------- 7.840583309478997
14 --------- 5.255034641721438

C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning: divide by zero encountered in scalar divide
  vif = 1. / (1. - r_squared_i)

15 --------- inf
15 --------- 7.380634506427232
15 --------- 1.421005001517573
16 --------- 8.083255010190323
16 --------- 1.624122752404011
17 --------- 7.257811920140003
17 --------- 15.59624383268298
17 --------- 1.825857047132431
18 --------- 1.5080839450032664
19 --------- 2.172088834824577
20 --------- 2.623397553527229
21 --------- 2.2959970812106167
22 --------- 7.360578319196446
22 --------- 2.1602387773102554
23 --------- 2.8686288267891467
24 --------- 6.458218003637277
24 --------- 2.8474118865638247
25 --------- 4.753198156284083
26 --------- 16.227354755948223
26 --------- 6.424377256363877
26 --------- 8.887080381808687
26 --------- 2.3804746142952653
27 --------- 8.609513476514548
27 --------- 13.06755093547673
27 --------- 3.5000400566546555
28 --------- 1.9087955874813773
29 --------- 17.006562234161628
29 --------- 10.730485153719197
29 --------- 2.3538497522950275
30 --------- 22.104855915136433
30 --------- 2.7971639638512915
31 --------- 3.424171203217697
32 --------- 10.175021454450922
32 --------- 6.408710354561292
32 --------- 1.0011511962625619
33 --------- 3.069197305397274
34 --------- 2.8091261600643724
35 --------- 20.249538381980678
35 --------- 15.864576541593774
35 --------- 1.833164974053215
36 --------- 1.5680839909542044
37 --------- 1.9307572353811682
38 --------- 4.331265056645249
39 --------- 9.390334396150173

In [61]:
column_to_be_kept

['pct_tl_open_L6M',
 'pct_tl_closed_L6M',
 'Tot_TL_closed_L12M',
 'pct_tl_closed_L12M',
 'Tot_Missed_Pmnt',
 'CC_TL',
 'Home_TL',
 'PL_TL',
 'Secured_TL',
 'Unsecured_TL',
 'Other_TL',
 'Age_Oldest_TL',
 'Age_Newest_TL',
 'time_since_recent_payment',
 'max_recent_level_of_deliq',
 'num_deliq_6_12mts',
 'num_times_60p_dpd',
 'num_std_12mts',
 'num_sub',
 'num_sub_6mts',
 'num_sub_12mts',
 'num_dbt',
 'num_dbt_12mts',
 'num_lss',
 'num_lss_12mts',
 'recent_level_of_deliq',
 'CC_enq_L12m',
 'PL_enq_L12m',
 'time_since_recent_enq',
 'enq_L3m',
 'NETMONTHLYINCOME',
 'Time_With_Curr_Empr',
 'pct_currentBal_all_TL',
 'CC_Flag',
 'PL_Flag',
 'pct_PL_enq_L6m_of_ever',
 'pct_CC_enq_L6m_of_ever',
 'HL_Flag',
 'GL_Flag']

In [62]:
dfn

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,enq_L3m,NETMONTHLYINCOME,Time_With_Curr_Empr,pct_currentBal_all_TL,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag
0,0.000,0.00,0,0.000,0,0,0,4,1,4,...,0,51000,114,0.798,0,1,0.000,0.0,1,0
1,0.000,0.00,0,0.000,0,0,0,0,0,1,...,0,19000,50,0.370,0,0,0.000,0.0,0,0
2,0.125,0.00,0,0.000,1,0,0,0,2,6,...,0,18,191,0.585,0,0,0.000,0.0,1,0
3,0.000,0.00,0,0.000,0,0,0,0,3,0,...,0,15000,75,0.000,0,0,0.000,0.0,0,0
4,0.000,0.00,1,0.167,0,0,0,0,6,0,...,4,0,154,0.000,0,0,0.429,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,0.333,0.00,0,0.000,0,0,0,0,0,3,...,1,18500,249,0.230,0,0,0.000,0.0,0,0
42060,0.000,0.25,1,0.250,0,0,0,0,2,2,...,0,25000,186,0.660,0,0,0.000,0.0,0,0
42061,0.500,0.50,1,0.500,0,0,0,0,0,2,...,2,18000,66,0.428,0,0,1.000,0.0,0,0
42062,0.000,0.00,1,0.500,0,0,0,0,0,2,...,0,12802,54,0.143,0,0,0.000,0.0,0,0
42063,0.000,0.00,0,0.000,0,0,0,0,1,0,...,1,16000,102,0.333,0,0,0.000,0.0,0,0

In [63]:
# Here After cleaning only 39 numeric columns are usefull ;--

# Anova Test

In [64]:
# First we need to create group of Resultant categorical column first

In [65]:
# g1 = df[df["Approved_Flag"].str.contains("P1")]["Total_TL"]
# g1 = df[df["Approved_Flag"].str.contains("P2")]["Total_TL"]
# g1 = df[df["Approved_Flag"].str.contains("P3")]["Total_TL"]
# g1 = df[df["Approved_Flag"].str.contains("P4")]["Total_TL"]

In [66]:

from scipy.stats import f_oneway

In [67]:

kept_column_numeric = []

for i in column_to_be_kept:
    a = list(df[i])
    b = list(df["Approved_Flag"])

    g1 = [value for value, group in zip(a,b) if group =="P1"]
    g2 = [value for value, group in zip(a,b) if group =="P2"]
    g3 = [value for value, group in zip(a,b) if group =="P3"]
    g4 = [value for value, group in zip(a,b) if group =="P4"]

    f_statics,p_value = f_oneway(g1,g2,g3,g4)

    if p_value <=.05:
        kept_column_numeric.append(i)

In [68]:
df[kept_column_numeric]

,pct_tl_open_L6M,pct_tl_closed_L6M,Tot_TL_closed_L12M,pct_tl_closed_L12M,Tot_Missed_Pmnt,CC_TL,Home_TL,PL_TL,Secured_TL,Unsecured_TL,...,time_since_recent_enq,enq_L3m,NETMONTHLYINCOME,Time_With_Curr_Empr,CC_Flag,PL_Flag,pct_PL_enq_L6m_of_ever,pct_CC_enq_L6m_of_ever,HL_Flag,GL_Flag
0,0.000,0.00,0,0.000,0,0,0,4,1,4,...,566,0,51000,114,0,1,0.000,0.0,1,0
1,0.000,0.00,0,0.000,0,0,0,0,0,1,...,209,0,19000,50,0,0,0.000,0.0,0,0
2,0.125,0.00,0,0.000,1,0,0,0,2,6,...,587,0,18,191,0,0,0.000,0.0,1,0
3,0.000,0.00,0,0.000,0,0,0,0,3,0,...,3951,0,15000,75,0,0,0.000,0.0,0,0
4,0.000,0.00,1,0.167,0,0,0,0,6,0,...,7,4,0,154,0,0,0.429,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,0.333,0.00,0,0.000,0,0,0,0,0,3,...,0,1,18500,249,0,0,0.000,0.0,0,0
42060,0.000,0.25,1,0.250,0,0,0,0,2,2,...,203,0,25000,186,0,0,0.000,0.0,0,0
42061,0.500,0.50,1,0.500,0,0,0,0,0,2,...,1,2,18000,66,0,0,1.000,0.0,0,0
42062,0.000,0.00,1,0.500,0,0,0,0,0,2,...,242,0,12802,54,0,0,0.000,0.0,0,0
42063,0.000,0.00,0,0.000,0,0,0,0,1,0,...,13,1,16000,102,0,0,0.000,0.0,0,0

In [69]:
# Another way to apply anova test

from scipy.stats import f_oneway

kept = []

for i in column_to_be_kept:

    g1 = df[df["Approved_Flag"] == "P1"][i]
    g2 = df[df["Approved_Flag"] == "P2"][i]
    g3 = df[df["Approved_Flag"] == "P3"][i]
    g4 = df[df["Approved_Flag"] == "P4"][i]

    f_stat, p_value = f_oneway(g1, g2, g3, g4)

    if p_value <= 0.05:
        kept.append(i)

print(kept)

['pct_tl_open_L6M', 'pct_tl_closed_L6M', 'Tot_TL_closed_L12M', 'pct_tl_closed_L12M', 'Tot_Missed_Pmnt', 'CC_TL', 'Home_TL', 'PL_TL', 'Secured_TL', 'Unsecured_TL', 'Other_TL', 'Age_Oldest_TL', 'Age_Newest_TL', 'time_since_recent_payment', 'max_recent_level_of_deliq', 'num_deliq_6_12mts', 'num_times_60p_dpd', 'num_std_12mts', 'num_sub', 'num_sub_6mts', 'num_sub_12mts', 'num_dbt', 'num_dbt_12mts', 'num_lss', 'recent_level_of_deliq', 'CC_enq_L12m', 'PL_enq_L12m', 'time_since_recent_enq', 'enq_L3m', 'NETMONTHLYINCOME', 'Time_With_Curr_Empr', 'CC_Flag', 'PL_Flag', 'pct_PL_enq_L6m_of_ever', 'pct_CC_enq_L6m_of_ever', 'HL_Flag', 'GL_Flag']

In [70]:
len(kept)

37

In [71]:
x=[]
for i in df.columns:
    if df[i].dtype == "object":
        print(i)
        x.append(i)

MARITALSTATUS
EDUCATION
GENDER
last_prod_enq2
first_prod_enq2
Approved_Flag

# Encording :----

In [72]:
super = df[x]
df[x]

,MARITALSTATUS,EDUCATION,GENDER,last_prod_enq2,first_prod_enq2,Approved_Flag
0,Married,12TH,M,PL,PL,P2
1,Single,GRADUATE,F,ConsumerLoan,ConsumerLoan,P2
2,Married,SSC,M,ConsumerLoan,others,P2
3,Married,POST-GRADUATE,M,AL,AL,P1
4,Married,12TH,M,ConsumerLoan,PL,P3
...,...,...,...,...,...,...
42059,Married,12TH,M,ConsumerLoan,ConsumerLoan,P4
42060,Married,SSC,M,others,others,P1
42061,Married,SSC,M,ConsumerLoan,others,P3
42062,Single,UNDER GRADUATE,F,ConsumerLoan,others,P2
42063,Married,SSC,M,others,others,P2

In [73]:
# We cant perform operation on categorical string data , so we use encoding to convert categorical to numeric conversion
# Nominal and ordinal

In [74]:
# Check category in each column

for i in df[x].columns:
    print(i)
    print(df[i].unique())

MARITALSTATUS
['Married' 'Single']
EDUCATION
['12TH' 'GRADUATE' 'SSC' 'POST-GRADUATE' 'UNDER GRADUATE' 'OTHERS'
 'PROFESSIONAL']
GENDER
['M' 'F']
last_prod_enq2
['PL' 'ConsumerLoan' 'AL' 'CC' 'others' 'HL']
first_prod_enq2
['PL' 'ConsumerLoan' 'others' 'AL' 'HL' 'CC']
Approved_Flag
['P2' 'P1' 'P3' 'P4']

In [75]:
# Education :-- Ordinal 
# SSC - 1
# 12th - 2
# Graduate - 3
# Under Graduate - 3
# Post Graduate - 4
# Others - 1
# Professional - 3

In [76]:
df.loc[df["EDUCATION"]=="12TH",["EDUCATION"]]=[2]
df.loc[df["EDUCATION"]=="SSC",["EDUCATION"]]=[1]
df.loc[df["EDUCATION"]=="GRADUATE",["EDUCATION"]]=[3]
df.loc[df["EDUCATION"]=="UNDER GRADUATE",["EDUCATION"]]=[3]
df.loc[df["EDUCATION"]=="POST-GRADUATE",["EDUCATION"]]=[4]
df.loc[df["EDUCATION"]=="OTHERS",["EDUCATION"]]=[1]
df.loc[df["EDUCATION"]=="PROFESSIONAL",["EDUCATION"]]=[3]

In [77]:
df["EDUCATION"].unique()

array([2, 3, 1, 4], dtype=object)

In [78]:
df["GENDER"].unique()

array(['M', 'F'], dtype=object)

In [79]:
df = pd.get_dummies(df , columns = ["GENDER","MARITALSTATUS","first_prod_enq2","last_prod_enq2"])

In [82]:
# Because after dummy variables coli=umn are break :--------------------------

df["MARITALSTATUS"].unique()

KeyError: 'MARITALSTATUS'

In [83]:
df

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,first_prod_enq2_ConsumerLoan,first_prod_enq2_HL,first_prod_enq2_PL,first_prod_enq2_others,last_prod_enq2_AL,last_prod_enq2_CC,last_prod_enq2_ConsumerLoan,last_prod_enq2_HL,last_prod_enq2_PL,last_prod_enq2_others
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,False,False,True,False,False,False,False,False,True,False
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,True,False,False,False,False,False,True,False,False,False
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,False,False,False,True,False,False,True,False,False,False
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,False,False,False,False,True,False,False,False,False,False
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,...,False,False,True,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,True,False,False,False,False,False,True,False,False,False
42060,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,False,False,False,True,False,False,False,False,False,True
42061,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,False,False,False,True,False,False,True,False,False,False
42062,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,False,False,False,True,False,False,True,False,False,False
42063,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,False,False,False,True,False,False,False,False,False,True

In [90]:
for i in df.columns:
    if type(df[i][0]) == str:
        print(i,"----",type(df[i][0]))

Approved_Flag ---- <class 'str'>

In [91]:
df["Approved_Flag"]

0        P2
1        P2
2        P2
3        P1
4        P3
         ..
42059    P4
42060    P1
42061    P3
42062    P2
42063    P2
Name: Approved_Flag, Length: 42064, dtype: object

In [ ]:
# Here Lets ConVert approve Flag 
# P1--1
#P2--2
# P3 ---3
# P4--4

In [92]:
df.loc[df["Approved_Flag"]=="P1",["Approved_Flag"]]=[1]
df.loc[df["Approved_Flag"]=="P2",["Approved_Flag"]]=[2]
df.loc[df["Approved_Flag"]=="P3",["Approved_Flag"]]=[3]
df.loc[df["Approved_Flag"]=="P4",["Approved_Flag"]]=[4]

In [93]:
df

,PROSPECTID,Total_TL,Tot_Closed_TL,Tot_Active_TL,Total_TL_opened_L6M,Tot_TL_closed_L6M,pct_tl_open_L6M,pct_tl_closed_L6M,pct_active_tl,pct_closed_tl,...,first_prod_enq2_ConsumerLoan,first_prod_enq2_HL,first_prod_enq2_PL,first_prod_enq2_others,last_prod_enq2_AL,last_prod_enq2_CC,last_prod_enq2_ConsumerLoan,last_prod_enq2_HL,last_prod_enq2_PL,last_prod_enq2_others
0,1,5,4,1,0,0,0.000,0.00,0.200,0.800,...,False,False,True,False,False,False,False,False,True,False
1,2,1,0,1,0,0,0.000,0.00,1.000,0.000,...,True,False,False,False,False,False,True,False,False,False
2,3,8,0,8,1,0,0.125,0.00,1.000,0.000,...,False,False,False,True,False,False,True,False,False,False
3,5,3,2,1,0,0,0.000,0.00,0.333,0.667,...,False,False,False,False,True,False,False,False,False,False
4,6,6,5,1,0,0,0.000,0.00,0.167,0.833,...,False,False,True,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42059,51332,3,0,3,1,0,0.333,0.00,1.000,0.000,...,True,False,False,False,False,False,True,False,False,False
42060,51333,4,2,2,0,1,0.000,0.25,0.500,0.500,...,False,False,False,True,False,False,False,False,False,True
42061,51334,2,1,1,1,1,0.500,0.50,0.500,0.500,...,False,False,False,True,False,False,True,False,False,False
42062,51335,2,1,1,0,0,0.000,0.00,0.500,0.500,...,False,False,False,True,False,False,True,False,False,False
42063,51336,1,0,1,0,0,0.000,0.00,1.000,0.000,...,False,False,False,True,False,False,False,False,False,True

In [94]:
for i in df.columns:
   
    print(i,"----",type(df[i][0]),"--------",df[i][0])

PROSPECTID ---- <class 'numpy.int64'> -------- 1
Total_TL ---- <class 'numpy.int64'> -------- 5
Tot_Closed_TL ---- <class 'numpy.int64'> -------- 4
Tot_Active_TL ---- <class 'numpy.int64'> -------- 1
Total_TL_opened_L6M ---- <class 'numpy.int64'> -------- 0
Tot_TL_closed_L6M ---- <class 'numpy.int64'> -------- 0
pct_tl_open_L6M ---- <class 'numpy.float64'> -------- 0.0
pct_tl_closed_L6M ---- <class 'numpy.float64'> -------- 0.0
pct_active_tl ---- <class 'numpy.float64'> -------- 0.2
pct_closed_tl ---- <class 'numpy.float64'> -------- 0.8
Total_TL_opened_L12M ---- <class 'numpy.int64'> -------- 0
Tot_TL_closed_L12M ---- <class 'numpy.int64'> -------- 0
pct_tl_open_L12M ---- <class 'numpy.float64'> -------- 0.0
pct_tl_closed_L12M ---- <class 'numpy.float64'> -------- 0.0
Tot_Missed_Pmnt ---- <class 'numpy.int64'> -------- 0
Auto_TL ---- <class 'numpy.int64'> -------- 0
CC_TL ---- <class 'numpy.int64'> -------- 0
Consumer_TL ---- <class 'numpy.int64'> -------- 0
Gold_TL ---- <class 'numpy.int64'> -------- 1
Home_TL ---- <class 'numpy.int64'> -------- 0
PL_TL ---- <class 'numpy.int64'> -------- 4
Secured_TL ---- <class 'numpy.int64'> -------- 1
Unsecured_TL ---- <class 'numpy.int64'> -------- 4
Other_TL ---- <class 'numpy.int64'> -------- 0
Age_Oldest_TL ---- <class 'numpy.int64'> -------- 72
Age_Newest_TL ---- <class 'numpy.int64'> -------- 18
time_since_recent_payment ---- <class 'numpy.int64'> -------- 549
num_times_delinquent ---- <class 'numpy.int64'> -------- 11
max_recent_level_of_deliq ---- <class 'numpy.int64'> -------- 29
num_deliq_6mts ---- <class 'numpy.int64'> -------- 0
num_deliq_12mts ---- <class 'numpy.int64'> -------- 0
num_deliq_6_12mts ---- <class 'numpy.int64'> -------- 0
num_times_30p_dpd ---- <class 'numpy.int64'> -------- 0
num_times_60p_dpd ---- <class 'numpy.int64'> -------- 0
num_std ---- <class 'numpy.int64'> -------- 21
num_std_6mts ---- <class 'numpy.int64'> -------- 5
num_std_12mts ---- <class 'numpy.int64'> -------- 11
num_sub ---- <class 'numpy.int64'> -------- 0
num_sub_6mts ---- <class 'numpy.int64'> -------- 0
num_sub_12mts ---- <class 'numpy.int64'> -------- 0
num_dbt ---- <class 'numpy.int64'> -------- 0
num_dbt_6mts ---- <class 'numpy.int64'> -------- 0
num_dbt_12mts ---- <class 'numpy.int64'> -------- 0
num_lss ---- <class 'numpy.int64'> -------- 0
num_lss_6mts ---- <class 'numpy.int64'> -------- 0
num_lss_12mts ---- <class 'numpy.int64'> -------- 0
recent_level_of_deliq ---- <class 'numpy.int64'> -------- 29
tot_enq ---- <class 'numpy.int64'> -------- 6
CC_enq ---- <class 'numpy.int64'> -------- 0
CC_enq_L6m ---- <class 'numpy.int64'> -------- 0
CC_enq_L12m ---- <class 'numpy.int64'> -------- 0
PL_enq ---- <class 'numpy.int64'> -------- 6
PL_enq_L6m ---- <class 'numpy.int64'> -------- 0
PL_enq_L12m ---- <class 'numpy.int64'> -------- 0
time_since_recent_enq ---- <class 'numpy.int64'> -------- 566
enq_L12m ---- <class 'numpy.int64'> -------- 0
enq_L6m ---- <class 'numpy.int64'> -------- 0
enq_L3m ---- <class 'numpy.int64'> -------- 0
EDUCATION ---- <class 'int'> -------- 2
AGE ---- <class 'numpy.int64'> -------- 48
NETMONTHLYINCOME ---- <class 'numpy.int64'> -------- 51000
Time_With_Curr_Empr ---- <class 'numpy.int64'> -------- 114
pct_of_active_TLs_ever ---- <class 'numpy.float64'> -------- 0.2
pct_opened_TLs_L6m_of_L12m ---- <class 'numpy.float64'> -------- 0.0
pct_currentBal_all_TL ---- <class 'numpy.float64'> -------- 0.798
CC_Flag ---- <class 'numpy.int64'> -------- 0
PL_Flag ---- <class 'numpy.int64'> -------- 1
pct_PL_enq_L6m_of_L12m ---- <class 'numpy.float64'> -------- 0.0
pct_CC_enq_L6m_of_L12m ---- <class 'numpy.float64'> -------- 0.0
pct_PL_enq_L6m_of_ever ---- <class 'numpy.float64'> -------- 0.0
pct_CC_enq_L6m_of_ever ---- <class 'numpy.float64'> -------- 0.0
HL_Flag ---- <class 'numpy.int64'> -------- 1
GL_Flag ---- <class 'numpy.int64'> -------- 0
Credit_Score ---- <class 'numpy.int64'> -------- 696
Approved_Flag ---- <class 'int'> -------- 2
GENDER_F ---- <class 'numpy.bool'> -------- False
GENDER_M ---- <class 'numpy.bool'> -------- True
MARITALSTATUS_Married ---- <class 'numpy.bool'> -------- True
MARITALSTATUS_Single ---- <class 'numpy.bool'> -------- False
first_prod_enq2_AL ---- <class 'numpy.bool'> -------- False
first_prod_enq2_CC ---- <class 'numpy.bool'> -------- False
first_prod_enq2_ConsumerLoan ---- <class 'numpy.bool'> -------- False
first_prod_enq2_HL ---- <class 'numpy.bool'> -------- False
first_prod_enq2_PL ---- <class 'numpy.bool'> -------- True
first_prod_enq2_others ---- <class 'numpy.bool'> -------- False
last_prod_enq2_AL ---- <class 'numpy.bool'> -------- False
last_prod_enq2_CC ---- <class 'numpy.bool'> -------- False
last_prod_enq2_ConsumerLoan ---- <class 'numpy.bool'> -------- False
last_prod_enq2_HL ---- <class 'numpy.bool'> -------- False
last_prod_enq2_PL ---- <class 'numpy.bool'> -------- True
last_prod_enq2_others ---- <class 'numpy.bool'> -------- False